### ISSUE TITLE
Which short description should we use for the project?

### ISSUE THREAD

**Issue by 0x5c** [miaowware/ctyparser#20]
Descriptions used throughout the project:
- A CTY.DAT parser for Python 3
- CTY.DAT parser for amateur radio
- `cty.dat` parsing and updating for Python.

We should really decide on one and stick to it.

**Comment by classabbyamp** [comment]
CTY.DAT parsing for Python 3 and amateur radio?

**Comment by 0x5c** [comment]
I wouldn't mention python3, seems like we consider python2 still worth being `python`, and that's the kind of thought that keeps me up at night.

I propose `CTY.DAT parser for modern amateur radio programs`

**Comment by classabbyamp** [comment]
sounds good to me

**Comment by 0x5c** [comment]
Added `A ` at the start, updated the files.

**Comment by 0x5c** [comment]
remains to update the repository's description field
