### ISSUE TITLE
Setup.py: full list of classifiers

### ISSUE THREAD

**Issue by 0x5c** [miaowware/ctyparser#23]
We need to add more classifiers to `setup.py`. @classabbyamp

**Comment by classabbyamp** [comment]
I think we should use these:

- Development Status :: 5 - Production/Stable
- Environment :: Console
- ~~Environment :: Plugins ???~~
- Intended Audience :: Developers
- ~~Intended Audience :: Science/Research ???~~
- ~~Intended Audience :: Telecommunications Industry ???~~
- Operating System :: OS Independent
- Topic :: Communications :: Ham Radio
- ~~Topic :: Scientific/Engineering ???~~
